import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "900"], 
});


export const metadata: Metadata = {
  title: "TegPro",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`antialiased ${montserrat.className}}`}
      >
                <Script
          strategy="afterInteractive"
          src="https://www.googletagmanager.com/gtag/js?id=G-BDH5DHXZTV"
        />
        <Script id="gtag-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-BDH5DHXZTV');
          `}
        </Script>
        {children}
      </body>
    </html>
  );
}
